name = 'ex_04'

tile_set = [
            [('corn', 0), ('gras', 0), ('corn', 0), ('gras', 0), ('corn', 0), ('corn', 0), ('corn', 2)],
            [('house', 0), ('house', 0), ('house', 0), ('house', 0), ('house', 0), ('house', 0), ('house', 6)],
            [('house', 1), ('tree', 4), ('gras', 0), ('gras', 0), ('gras', 0), ('gras', 0), ('gras', 0)],
            [('corn', 1), ('gras', 0), ('gras', 0), ('gras', 0), ('rail', 1), ('rail', 0), ('gras', 0)],
            [('tree', 0), ('gras', 0), ('house', 2), ('house', 0), ('gras', 0), ('tree', 10), ('gras', 0)], 
            [('water', 0), ('water', 1), ('water', 0), ('rail', 0), ('house', 1), ('rail', 0), ('rail', 1)],
            [('rail', 0), ('tree', 4), ('rail', 0), ('tree', 0), ('tree', 17), ('tree', 0), ('rail', 1)],
            [('water', 0), ('water', 0), ('water', 0), ('tree', 4), ('house', 1), ('gras', 0), ('water', 1)],
            [('corn', 0), ('corn', 0), ('corn', 0), ('corn', 0), ('gras', 0), ('corn', 0), ('corn', 2)],
            [('gras', 0), ('gras', 0), ('gras', 0), ('water', 0), ('gras', 0), ('water', 0), ('water', 1)],
            [('house', 1), ('corn', 1), ('gras', 0), ('gras', 0), ('house', 1), ('corn', 1), ('gras', 0)],
            [('gras', 0), ('gras', 0), ('gras', 0), ('gras', 0), ('corn', 1), ('gras', 0), ('gras', 0)],
            [('house', 0), ('house', 0), ('house', 0), ('gras', 0), ('house', 0), ('gras', 0), ('house', 5)],
            [('gras', 0), ('tree', 4), ('rail', 0), ('rail', 0), ('rail', 0), ('rail', 0), ('rail', 1)],
            [('water', 0), ('house', 2), ('house', 0), ('water', 0), ('gras', 0), ('gras', 0), ('water', 1)],
            [('water', 0), ('tree', 10), ('tree', 0), ('gras', 0), ('gras', 0), ('water', 1), ('gras', 0)],
            [('rail', 1), ('gras', 0), ('gras', 0), ('gras', 0), ('corn', 0), ('gras', 0), ('gras', 0)],
            [('corn', 1), ('tree', 0), ('house', 1), ('gras', 0), ('tree', 0), ('gras', 0), ('tree', 17)],
            [('corn', 0), ('corn', 0), ('corn', 0), ('corn', 0), ('corn', 0), ('corn', 0), ('corn', 3)],
            [('gras', 0), ('corn', 1), ('gras', 0), ('gras', 0), ('gras', 0), ('house', 1), ('gras', 0)],
            [('corn', 0), ('corn', 0), ('tree', 4), ('corn', 0), ('gras', 0), ('gras', 0), ('corn', 3)],
            [('house', 2), ('house', 0), ('gras', 0), ('gras', 0), ('gras', 0), ('gras', 0), ('gras', 0)],
            [('house', 0), ('corn', 1), ('gras', 0), ('gras', 0), ('house', 0), ('corn', 1), ('house', 3)],
            [('gras', 0), ('corn', 0), ('corn', 0), ('corn', 0), ('corn', 0), ('gras', 0), ('corn', 2)],
            [('gras', 0), ('tree', 0), ('tree', 0), ('gras', 0), ('tree', 0), ('tree', 0), ('tree', 24)],
            ]
